/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatrociniosRouteImport } from './routes/patrocinios'
import { Route as ComprarRouteImport } from './routes/comprar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmissaoIndexRouteImport } from './routes/admissao.index'
import { Route as ConfirmacaoReferenceRouteImport } from './routes/confirmacao.$reference'
import { Route as AdmissaoObrigadoRouteImport } from './routes/admissao.obrigado'

const PatrociniosRoute = PatrociniosRouteImport.update({
  id: '/patrocinios',
  path: '/patrocinios',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarRoute = ComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissaoIndexRoute = AdmissaoIndexRouteImport.update({
  id: '/admissao/',
  path: '/admissao/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacaoReferenceRoute = ConfirmacaoReferenceRouteImport.update({
  id: '/confirmacao/$reference',
  path: '/confirmacao/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissaoObrigadoRoute = AdmissaoObrigadoRouteImport.update({
  id: '/admissao/obrigado',
  path: '/admissao/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comprar': typeof ComprarRoute
  '/patrocinios': typeof PatrociniosRoute
  '/admissao/obrigado': typeof AdmissaoObrigadoRoute
  '/confirmacao/$reference': typeof ConfirmacaoReferenceRoute
  '/admissao/': typeof AdmissaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comprar': typeof ComprarRoute
  '/patrocinios': typeof PatrociniosRoute
  '/admissao/obrigado': typeof AdmissaoObrigadoRoute
  '/confirmacao/$reference': typeof ConfirmacaoReferenceRoute
  '/admissao': typeof AdmissaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comprar': typeof ComprarRoute
  '/patrocinios': typeof PatrociniosRoute
  '/admissao/obrigado': typeof AdmissaoObrigadoRoute
  '/confirmacao/$reference': typeof ConfirmacaoReferenceRoute
  '/admissao/': typeof AdmissaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/comprar'
    | '/patrocinios'
    | '/admissao/obrigado'
    | '/confirmacao/$reference'
    | '/admissao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/comprar'
    | '/patrocinios'
    | '/admissao/obrigado'
    | '/confirmacao/$reference'
    | '/admissao'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/comprar'
    | '/patrocinios'
    | '/admissao/obrigado'
    | '/confirmacao/$reference'
    | '/admissao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ComprarRoute: typeof ComprarRoute
  PatrociniosRoute: typeof PatrociniosRoute
  AdmissaoObrigadoRoute: typeof AdmissaoObrigadoRoute
  ConfirmacaoReferenceRoute: typeof ConfirmacaoReferenceRoute
  AdmissaoIndexRoute: typeof AdmissaoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patrocinios': {
      id: '/patrocinios'
      path: '/patrocinios'
      fullPath: '/patrocinios'
      preLoaderRoute: typeof PatrociniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar': {
      id: '/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof ComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissao/': {
      id: '/admissao/'
      path: '/admissao'
      fullPath: '/admissao/'
      preLoaderRoute: typeof AdmissaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacao/$reference': {
      id: '/confirmacao/$reference'
      path: '/confirmacao/$reference'
      fullPath: '/confirmacao/$reference'
      preLoaderRoute: typeof ConfirmacaoReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissao/obrigado': {
      id: '/admissao/obrigado'
      path: '/admissao/obrigado'
      fullPath: '/admissao/obrigado'
      preLoaderRoute: typeof AdmissaoObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ComprarRoute: ComprarRoute,
  PatrociniosRoute: PatrociniosRoute,
  AdmissaoObrigadoRoute: AdmissaoObrigadoRoute,
  ConfirmacaoReferenceRoute: ConfirmacaoReferenceRoute,
  AdmissaoIndexRoute: AdmissaoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
